package com.example.smartsight;

import androidx.lifecycle.LiveData;
import androidx.room.*;

import java.util.List;

@Dao
public interface ItemDao {

    @Insert
    void insert(SavedItem item);

    // NEW: insert and return the autogenerated itemId
    @Insert
    long insertAndGetId(SavedItem item);

    @Update
    void update(SavedItem item);

    @Delete
    void delete(SavedItem item);

    @Query("SELECT * FROM saved_items ORDER BY scanDate DESC")
    LiveData<List<SavedItem>> getAllItems();

    @Query("SELECT * FROM saved_items")
    List<SavedItem> getAllItemsSync();

    @Query("UPDATE saved_items SET customName = :newName WHERE itemId = :itemId")
    void updateName(int itemId, String newName);
}
